#!/usr/bin/env php
<?php

if (!is_file('.composer.json')) {
    echo('There is no ".composer.json" template file in the current directory "' . getcwd() . '", make sure you are in the right directory and a template exists.');
    exit(1);
}

/**
 * @param array $joinedManifest
 * @param array $manifestData
 * @param string $sectionKey
 * @return array
 */
function mergeArraySection($joinedManifest, $manifestData, $sectionKey)
{
    if (isset($manifestData[$sectionKey])) {
        if (!isset($joinedManifest[$sectionKey])) {
            $joinedManifest[$sectionKey] = [];
        }
        $joinedManifest[$sectionKey] = array_merge($joinedManifest[$sectionKey], $manifestData[$sectionKey]);
    }

    return $joinedManifest;
}

/**
 * @param array $joinedManifest
 * @param array $manifestData
 * @param string $sectionKey
 * @param string $packageName
 * @return array
 */
function mergeAutoloadSection($joinedManifest, $manifestData, $sectionKey, $packageName)
{
    if (isset($manifestData[$sectionKey])) {
        if (!isset($joinedManifest[$sectionKey])) {
            $joinedManifest[$sectionKey] = [];
        }
        foreach ($manifestData[$sectionKey] as $autoloadType => $mappings) {
            foreach ($mappings as $namespace => $folders) {
                if (!is_array($folders)) {
                    $folders = [$folders];
                }
                $folders = array_map(function ($folder) use ($packageName) {
                    return implode('/', [$packageName, $folder]);
                }, $folders);

                if (!isset($joinedManifest[$sectionKey][$autoloadType][$namespace])) {
                    $joinedManifest[$sectionKey][$autoloadType][$namespace] = [];
                }

                $joinedManifest[$sectionKey][$autoloadType][$namespace] = array_merge($joinedManifest[$sectionKey][$autoloadType][$namespace], $folders);
            }
        }
    }

    return $joinedManifest;
}

$composerManifests = glob('*/composer.json');

$joinedManifest = json_decode(file_get_contents('.composer.json'), true);
// As JSON doesn't allow for any comments this is added as manifest key.
$joinedManifest['extra']['neos']['warning'] = 'AUTOGENERATED FILE, ONLY MODIFY THE .composer.json IN THIS DIRECTORY AND RUN THE MERGE SCRIPT.';

$joinedRepositoryPackages = [];

foreach ($composerManifests as $manifestFilepath) {
    $packageName = trim(dirname($manifestFilepath), '/');
    $manifestData = json_decode(file_get_contents($manifestFilepath), true);

    $joinedRepositoryPackages[] = $manifestData['name'];

    foreach (['require', 'require-dev', 'suggest'] as $arraySectionKey) {
        $joinedManifest = mergeArraySection($joinedManifest, $manifestData, $arraySectionKey);
    }

    foreach (['autoload', 'autoload-dev'] as $autoloadSectionKey) {
        $joinedManifest = mergeAutoloadSection($joinedManifest, $manifestData, $autoloadSectionKey, $packageName);
    }

    if (isset($manifestData['extra'])) {
        $extras = $manifestData['extra'];

        if (isset($extras['neos']['package-key'])) {
            unset($extras['neos']['package-key']);
        }

        if (array_key_exists('applied-flow-migrations', $extras)) {
            unset($extras['applied-flow-migrations']);
        }

        if (isset($extras['neos']['installer-resource-folders']) && is_array($extras['neos']['installer-resource-folders'])) {
            $extras['neos']['installer-resource-folders'] = array_map(function ($resourceFolder) use ($packageName) {
                return $packageName . '/' . $resourceFolder;
            }, $extras['neos']['installer-resource-folders']);
        }

        $joinedManifest['extra'] = array_merge_recursive($joinedManifest['extra'], $extras);
    }

    if (isset($manifestData['replace'])) {
        $replace = $manifestData['replace'];
        $joinedManifest['replace'] = array_merge_recursive($joinedManifest['replace'], $replace);
    }
}

foreach ($joinedRepositoryPackages as $containedPackageName) {
    unset($joinedManifest['require'][$containedPackageName]);
    $joinedManifest['replace'][$containedPackageName] = 'self.version';
}

$joinedComposerJson = json_encode($joinedManifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . PHP_EOL;
file_put_contents('composer.json', $joinedComposerJson);

echo('Written the following merged ' . getcwd() . '/composer.json' . PHP_EOL . PHP_EOL);
echo $joinedComposerJson;

exit(0);
